"""
Gemini HAM Radio Log Parser
============================
Reads the most recent session from the recordings/ folder,
uploads the DSP-filtered .wav audio + Whisper .log transcript
to Google Gemini 1.5 Pro, and extracts a structured HAM radio
logbook in JSON format.

Usage:
    python3 gemini_parser.py
    python3 gemini_parser.py recordings/session_20260320_120000
"""

import os
import sys
import json
import glob
import datetime
import google.generativeai as genai
from dotenv import load_dotenv

load_dotenv()

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
if not GEMINI_API_KEY or GEMINI_API_KEY == "your_gemini_api_key_here":
    print("❌ ERROR: Please set your GEMINI_API_KEY in the .env file.")
    print("   Open .env and replace 'your_gemini_api_key_here' with your actual key.")
    sys.exit(1)

genai.configure(api_key=GEMINI_API_KEY)

RECORDINGS_DIR = "recordings"
OUTPUT_DIR = "logs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

HAM_LOG_PROMPT = """You are an expert amateur (HAM) radio operator and certified log keeper.

I am providing you with two things:
1. An AUDIO RECORDING of a HAM radio QSO (contact), which has been DSP-filtered to remove static/noise.
2. A TEXT TRANSCRIPT of the same QSO, generated by Whisper AI (may contain minor errors).

Your job is to carefully listen to the audio AND read the transcript, then extract a structured amateur radio logbook entry.

IMPORTANT RULES:
- Callsigns use the NATO phonetic alphabet. Convert them back to their actual alphanumeric form.
  Example: "Whiskey Two Papa Victor Foxtrot" = "W2PVF"
  Example: "Lima Uniform One Zebra Echo" = "LU1ZE"
- Signal reports use the RST system (Readability, Strength, Tone). "Nine plus" = 59+
- Extract ALL distinct stations/operators mentioned in the QSO.
- Use UTC timestamps from the transcript log entries.
- If information is unclear or missing, mark it as "UNKNOWN".

Return ONLY valid JSON in exactly this format (no markdown, no explanation):
{
  "qso_entries": [
    {
      "date_utc": "YYYY-MM-DD",
      "time_utc": "HH:MM",
      "callsign": "THEIR CALLSIGN",
      "operator_name": "THEIR NAME",
      "qth": "THEIR LOCATION",
      "frequency_khz": "FREQUENCY if mentioned",
      "mode": "SSB/AM/CW/FM",
      "rst_sent": "SIGNAL REPORT WE SENT THEM",
      "rst_received": "SIGNAL REPORT THEY SENT US",
      "remarks": "Brief summary of the contact"
    }
  ],
  "session_summary": "A one-paragraph summary of the entire radio session",
  "dialogue": [
    {"speaker": "{callsign}", "text": "Corrected and cleaned up speech text"}
  ]
}
"""

TEXT_ONLY_PROMPT = """You are an expert amateur (HAM) radio log keeper.
I am providing you with a TEXT TRANSCRIPT of a HAM radio contact, generated by a speech-to-text AI. 

IMPORTANT RULES for extraction:
- Extract ONE primary QSO entry summarizing the contact. Do NOT create a new entry for every sentence.
- Callsigns use the NATO phonetic alphabet (e.g., "Whiskey Two Papa Victor Foxtrot" = "W2PVF").
- If information is unclear, use "UNKNOWN".

Return ONLY valid JSON in exactly this format (no markdown explanations):
{
  "qso_entries": [
    {
      "date_utc": "YYYY-MM-DD",
      "time_utc": "HH:MM",
      "callsign": "THEIR CALLSIGN",
      "operator_name": "THEIR NAME",
      "qth": "THEIR LOCATION",
      "mode": "SSB/CW",
      "rst_received": "RST",
      "remarks": "Summary of contact"
    }
  ],
  "session_summary": "Overall summary paragraph",
  "dialogue": [{"speaker": "You/They", "text": "Cleaned up text"}]
}
"""

def find_latest_session(base_path=None):
    """Find the most recent session pair (.wav + .log) in recordings/"""
    if base_path:
        wav = base_path if base_path.endswith(".wav") else base_path + ".wav"
        log = base_path.replace(".wav", "") + ".log"
        if os.path.exists(wav) and os.path.exists(log):
            return wav, log
        print(f"❌ Could not find both files: {wav} and {log}")
        sys.exit(1)
    
    wav_files = sorted(glob.glob(os.path.join(RECORDINGS_DIR, "session_*.wav")))
    if not wav_files:
        print(f"❌ No session recordings found in {RECORDINGS_DIR}/")
        print("   Run live_transcribe.py first to record a session.")
        sys.exit(1)
    
    latest_wav = wav_files[-1]
    latest_log = latest_wav.replace(".wav", ".log")
    
    if not os.path.exists(latest_log):
        print(f"⚠️  Warning: No matching .log file found for {latest_wav}")
        print("   Proceeding with audio only...")
        latest_log = None
    
    return latest_wav, latest_log

def ask_local_gemma(wav_path, transcript_text):
    print("\n🌐 Network/API issue detected. Falling back to local offline model...")
    
    # 0. Check for LM Studio Local Server (Fastest Text Fallback)
    try:
        import urllib.request
        import json
        
        # Probe LM Studio Model Endpoint
        url = "http://localhost:1234/v1/models"
        req = urllib.request.Request(url)
        with urllib.request.urlopen(req, timeout=1) as response:
            if response.status == 200:
                print("   ✅ LM Studio Local Server detected! Forwarding transcript to active model...")
                
                full_prompt = HAM_LOG_PROMPT
                if transcript_text:
                    full_prompt += f"\n\n--- WHISPER TRANSCRIPT ---\n{transcript_text}\n--- END TRANSCRIPT ---"
                
                data = {
                    "model": "local-model",
                    "messages": [
                        {"role": "user", "content": full_prompt}
                    ],
                    "temperature": 0.1,
                    "max_tokens": 1024
                }
                
                chat_url = "http://localhost:1234/v1/chat/completions"
                chat_req = urllib.request.Request(chat_url, data=json.dumps(data).encode("utf-8"), headers={"Content-Type": "application/json"})
                with urllib.request.urlopen(chat_req, timeout=60) as chat_response:
                    result = json.loads(chat_response.read().decode())
                    print("   🧠 Running inference via LM Studio...")
                    return result["choices"][0]["message"]["content"].strip()
    except Exception:
        print("   (LM Studio local server not detected or failed. Proceeding to MLX/GGUF...)")

    model_path = os.environ.get("GEMMA_MODEL_PATH", "mlx-community/gemma-3-4b-it")
    print(f"   Targeting local model: {model_path}...")
    
    # 1. GGUF Model Handling (Standard CPU/Metal bindings)
    if model_path.endswith(".gguf") or ".gguf" in os.path.basename(model_path):
        print("   Detected .gguf format. Attempting to use llama-cpp-python...")
        try:
            from llama_cpp import Llama
        except ImportError:
            print("❌ llama-cpp-python is not installed. Run `pip install llama-cpp-python` to use GGUF models.")
            return None
            
        try:
            # We initialize llama_cpp with Metal GPU offloading if available (n_gpu_layers=-1)
            llm = Llama(model_path=model_path, n_ctx=4096, n_gpu_layers=-1, verbose=False)
            full_prompt = TEXT_ONLY_PROMPT
            if transcript_text:
                full_prompt += f"\n\n--- WHISPER TRANSCRIPT ---\n{transcript_text}\n--- END TRANSCRIPT ---"
            
            print("   🧠 Running local GGUF inference (using Whisper text transcript logic)...")
            response = llm.create_chat_completion(
                messages=[
                    {"role": "user", "content": full_prompt}
                ],
                max_tokens=1024,
                temperature=0.1
            )
            return response["choices"][0]["message"]["content"].strip()
            
        except Exception as local_e:
            print(f"❌ Local GGUF fallback failed: {local_e}")
            return None

    # 2. MLX Model Handling (Native Apple Silicon VLM format)
    else:
        print("   Attempting to use mlx-vlm for native Apple Silicon multimodal inference...")
        try:
            from mlx_vlm import load, generate
        except ImportError:
            print("❌ mlx-vlm is not installed. Run `pip install mlx-vlm` or set a .gguf path.")
            return None
            
        try:
            model, processor = load(model_path)
            
            full_prompt = HAM_LOG_PROMPT
            if transcript_text:
                full_prompt += f"\n\n--- WHISPER TRANSCRIPT ---\n{transcript_text}\n--- END TRANSCRIPT ---"

            messages = [
                {"role": "user", "content": [
                    {"type": "audio", "audio": wav_path},
                    {"type": "text", "text": full_prompt}
                ]}
            ]
            
            prompt = processor.apply_chat_template(messages, add_generation_prompt=True)
            print("   🧠 Running local inference via mlx-vlm (this may take a moment)...")
            response_text = generate(model, processor, prompt, max_tokens=1024, temperature=0.1)
            
            return response_text.strip()
            
        except Exception as e:
            if "Model type" in str(e) and "not supported" in str(e):
                print(f"   ⚠️ This model lacks multimodal configs ({e}). Switching to text-only mlx-lm...")
                try:
                    from mlx_lm import load as lm_load
                    from mlx_lm import generate as lm_generate
                    
                    lm_model, lm_tokenizer = lm_load(model_path)
                    
                    full_prompt = TEXT_ONLY_PROMPT
                    if transcript_text:
                        full_prompt += f"\n\n--- WHISPER TRANSCRIPT ---\n{transcript_text}\n--- END TRANSCRIPT ---"
                        
                    messages = [{"role": "user", "content": full_prompt}]
                    prompt = lm_tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
                    
                    print("   🧠 Running local text inference via mlx-lm using Whisper transcript...")
                    response_text = lm_generate(lm_model, lm_tokenizer, prompt=prompt, max_tokens=1024)
                    return response_text.strip()
                except Exception as lm_e:
                    print(f"❌ Text-only MLX fallback failed: {lm_e}")
                    return None
            else:
                print(f"❌ Local MLX fallback failed: {e}")
                return None

def upload_and_parse(wav_path, log_path):
    """Upload audio to Gemini and extract structured HAM log (with local Gemma fallback)."""
    
    print(f"\n📁 Session Files:")
    print(f"   Audio: {wav_path}")
    print(f"   Log:   {log_path or 'N/A'}")
    
    # Read the transcript text
    transcript_text = ""
    if log_path and os.path.exists(log_path):
        with open(log_path, "r", encoding="utf-8") as f:
            transcript_text = f.read()
    
    raw_text = None
    try:
        print(f"\n📤 Uploading audio to Gemini File API...")
        audio_file = genai.upload_file(wav_path, mime_type="audio/wav")
        print(f"   ✅ Uploaded: {audio_file.name}")
        
        # Build the full prompt with transcript context
        full_prompt = HAM_LOG_PROMPT
        if transcript_text:
            full_prompt += f"\n\n--- WHISPER TRANSCRIPT ---\n{transcript_text}\n--- END TRANSCRIPT ---"
        
        print(f"\n🧠 Sending to Gemini 2.5 Flash for analysis...")
        model = genai.GenerativeModel("models/gemini-2.5-flash")
        
        response = model.generate_content(
            [full_prompt, audio_file],
            generation_config=genai.GenerationConfig(
                temperature=0.1,  # Low temperature for factual extraction
            )
        )
        
        # Parse the JSON response
        raw_text = response.text.strip()
    except Exception as e:
        print(f"\n⚠️ Gemini API failed: {e}")
        raw_text = ask_local_gemma(wav_path, transcript_text)
        
    if not raw_text:
        return None
        
    # Strip markdown code fences if wrapped
    if raw_text.startswith("```"):
        raw_text = raw_text.split("\n", 1)[1]
        if raw_text.endswith("```"):
            raw_text = raw_text[:-3].strip()
    
    try:
        log_data = json.loads(raw_text)
    except json.JSONDecodeError:
        print("\n⚠️  Gemini returned non-JSON. Raw response:")
        print(raw_text)
        return None
    
    return log_data

def display_log(log_data):
    """Pretty-print the structured HAM log."""
    print("\n" + "="*65)
    print("📋 STRUCTURED HAM RADIO LOGBOOK")
    print("="*65)
    
    if "session_summary" in log_data:
        print(f"\n📝 Summary: {log_data['session_summary']}")
    
    entries = log_data.get("qso_entries", [])
    if not entries:
        print("\n⚠️  No QSO entries extracted.")
        return
    
    print(f"\n{'#':<4} {'Date':<12} {'Time':<7} {'Callsign':<10} {'Name':<12} {'QTH':<20} {'RST S/R':<10} {'Mode':<5}")
    print("-"*80)
    
    for i, entry in enumerate(entries, 1):
        print(f"{i:<4} "
              f"{entry.get('date_utc', '?'):<12} "
              f"{entry.get('time_utc', '?'):<7} "
              f"{entry.get('callsign', '?'):<10} "
              f"{entry.get('operator_name', '?'):<12} "
              f"{entry.get('qth', '?'):<20} "
              f"{entry.get('rst_sent', '?')}/{entry.get('rst_received', '?'):<6} "
              f"{entry.get('mode', '?'):<5}")
        if entry.get("remarks"):
            print(f"     💬 {entry['remarks']}")
    
    print("-"*80)
    
    dialogue = log_data.get("dialogue", [])
    if dialogue:
        print("\n💬 FULL DIALOGUE (Corrected):")
        for line in dialogue:
            speaker = line.get("speaker", "Unknown")
            text = line.get("text", "")
            print(f"   {speaker}: {text}")
        print("-"*80)

def save_log(log_data, wav_path):
    """Save the structured log as a JSON file."""
    session_name = os.path.basename(wav_path).replace(".wav", "")
    output_path = os.path.join(OUTPUT_DIR, f"{session_name}_log.json")
    
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(log_data, f, indent=2, ensure_ascii=False)
    
    print(f"\n✅ Structured log saved to: {output_path}")
    return output_path

def main():
    print("="*65)
    print("📡 GEMINI HAM RADIO LOG PARSER")
    print("="*65)
    
    # Accept optional path argument
    base_path = sys.argv[1] if len(sys.argv) > 1 else None
    wav_path, log_path = find_latest_session(base_path)
    
    log_data = upload_and_parse(wav_path, log_path)
    
    if log_data:
        display_log(log_data)
        save_log(log_data, wav_path)
        
        # Cleanup uploaded file from Gemini
        print("\n🧹 Cleaning up uploaded files from Gemini servers...")
        try:
            for f in genai.list_files():
                try:
                    genai.delete_file(f.name)
                except:
                    pass
            print("   ✅ Done!")
        except Exception as cleanup_error:
            print(f"   ⚠️ Could not connect to Gemini for cleanup (Network offline). Files will be cleaned up later.")

if __name__ == "__main__":
    main()
